# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icat < Formula
  desc "Command line tool for displaying images in the terminal"
  homepage "https://github.com/hilli/icat"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hilli/icat/releases/download/v0.0.1/icat_Darwin_x86_64.tar.gz"
      sha256 "c227f6df6d8b1da55ca991b7b2efe5cb803fcc58f6ae25c296fbd84aa70ba9d0"

      def install
        bin.install "icat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hilli/icat/releases/download/v0.0.1/icat_Darwin_arm64.tar.gz"
      sha256 "622bc7cb5cb8d4acc4a8d67d1886ea6e850dd7db2e1284d3eb0d1cacca118c27"

      def install
        bin.install "icat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hilli/icat/releases/download/v0.0.1/icat_Linux_x86_64.tar.gz"
        sha256 "1fb5c0cd7959da27da4c035fc2fa98e447ef177b20056a89ba1705df1ec95da5"

        def install
          bin.install "icat"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hilli/icat/releases/download/v0.0.1/icat_Linux_arm64.tar.gz"
        sha256 "1262da79b7232270ec2529eacb011ade96dbb775af8c8e659324247960aafbe4"

        def install
          bin.install "icat"
        end
      end
    end
  end
end
