# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icat < Formula
  desc "Command line tool for displaying images in the terminal"
  homepage "https://github.com/hilli/icat"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hilli/icat/releases/download/v0.0.1/icat_Darwin_x86_64.tar.gz"
      sha256 "9b38c473ab99bb3f45b9ff68c4b558015667fd49e61278b5e8400bb4de0d1065"

      def install
        bin.install "icat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hilli/icat/releases/download/v0.0.1/icat_Darwin_arm64.tar.gz"
      sha256 "9c2d1baf63c0c2128985c8bfa2c8dd32f28469b022f1ce9bb9187ef539acbb7a"

      def install
        bin.install "icat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hilli/icat/releases/download/v0.0.1/icat_Linux_x86_64.tar.gz"
        sha256 "807ac36e2dcacd278a7ab3007f986b7d9b9f183354a1441fcfe66be872f0a35b"

        def install
          bin.install "icat"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hilli/icat/releases/download/v0.0.1/icat_Linux_arm64.tar.gz"
        sha256 "d606e8b8c014148abae88336318020ed2f34b3a6a716182fad38a3d276cf241a"

        def install
          bin.install "icat"
        end
      end
    end
  end
end
