# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kefw2 < Formula
  desc "Command for handling KEF W2 platform speakers (LSX Wireless II (LT)/LS50 Wireless II/LS60 Wireless)"
  homepage "https://github.com/hilli/go-kef-w2"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hilli/go-kef-w2/releases/download/v0.0.3/go-kef-w2_Darwin_x86_64.tar.gz"
      sha256 "dc2770a3d9330a410943735a1a7ace0cd6f4f08fae499cb42e86538969d5fa6a"

      def install
        bin.install "kefw2"
        bash_completion.install "completions/kefw2.bash" => "kefw2"
        zsh_completion.install "completions/kefw2.zsh" => "_kefw2"
        fish_completion.install "completions/kefw2.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hilli/go-kef-w2/releases/download/v0.0.3/go-kef-w2_Darwin_arm64.tar.gz"
      sha256 "7edfadea5d11a414d553c2b1d6de3eb801183c0c0ab8ee0deca8ec4045b18cd6"

      def install
        bin.install "kefw2"
        bash_completion.install "completions/kefw2.bash" => "kefw2"
        zsh_completion.install "completions/kefw2.zsh" => "_kefw2"
        fish_completion.install "completions/kefw2.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hilli/go-kef-w2/releases/download/v0.0.3/go-kef-w2_Linux_x86_64.tar.gz"
        sha256 "746f34efd2b105e2061abfc3fa632eadb68d07e441cf5c1ad7b5f17d12845efd"

        def install
          bin.install "kefw2"
          bash_completion.install "completions/kefw2.bash" => "kefw2"
          zsh_completion.install "completions/kefw2.zsh" => "_kefw2"
          fish_completion.install "completions/kefw2.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hilli/go-kef-w2/releases/download/v0.0.3/go-kef-w2_Linux_arm64.tar.gz"
        sha256 "93d94b314c0d25cf795ed37a08bfb885a432f5e483fe8270e8a05d7142a338bf"

        def install
          bin.install "kefw2"
          bash_completion.install "completions/kefw2.bash" => "kefw2"
          zsh_completion.install "completions/kefw2.zsh" => "_kefw2"
          fish_completion.install "completions/kefw2.fish"
        end
      end
    end
  end
end
