# This file was generated by GoReleaser. DO NOT EDIT.
cask "imapsync-go" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "e499b57221c49af302f409dc5d1e771746e3bd6531ef82eb3aab50c6022fb899"
      url "https://github.com/hilli/imapsync-go/releases/download/v#{version}/imapsync-go_Darwin_arm64.tar.gz",
        verified: "github.com/hilli/imapsync-go/"
    end
    on_intel do
      sha256 "dbffa1c68a178c77d020f8ef9cc27ed7b84008fd93171adee804c6c4a9ab2c9d"
      url "https://github.com/hilli/imapsync-go/releases/download/v#{version}/imapsync-go_Darwin_x86_64.tar.gz",
        verified: "github.com/hilli/imapsync-go/"
    end
  end
  on_linux do
    on_arm do
      sha256 "ab9e06a7770897e6cf0cda9456f693ebaee765f2f38529517757d13228f2a7b0"
      url "https://github.com/hilli/imapsync-go/releases/download/v#{version}/imapsync-go_Linux_arm64.tar.gz",
        verified: "github.com/hilli/imapsync-go/"
    end
    on_intel do
      sha256 "f5e3889abd6c8fc086a40c6e8d83a7653f32cf570082496189508fc84233f521"
      url "https://github.com/hilli/imapsync-go/releases/download/v#{version}/imapsync-go_Linux_x86_64.tar.gz",
        verified: "github.com/hilli/imapsync-go/"
    end
  end

  name "imapsync-go"
  desc "Concurrent IMAP account synchronisation"
  homepage "https://github.com/hilli/imapsync-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imapsync-go"
  bash_completion "completions/imapsync-go.bash"
  fish_completion "completions/imapsync-go.fish"
  zsh_completion "completions/imapsync-go.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/imapsync-go"]
    end
  end

  # No zap stanza required
end
