# This file was generated by GoReleaser. DO NOT EDIT.
cask "imapsync-go" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "07e577210c6248a73327376ddb4d712b25440b0f192129873118435c26d28d18"
      url "https://github.com/hilli/imapsync-go/releases/download/v#{version}/imapsync-go_Darwin_arm64.tar.gz",
        verified: "github.com/hilli/imapsync-go/"
    end
    on_intel do
      sha256 "883ab4fc5dae186164ffdc1d639113bd60cbb34168cd1205649e925451024348"
      url "https://github.com/hilli/imapsync-go/releases/download/v#{version}/imapsync-go_Darwin_x86_64.tar.gz",
        verified: "github.com/hilli/imapsync-go/"
    end
  end
  on_linux do
    on_arm do
      sha256 "0882998c7128e8fc3b129f1b6a925f71fe699b7f3e064a3d5e14846cb9ec291c"
      url "https://github.com/hilli/imapsync-go/releases/download/v#{version}/imapsync-go_Linux_arm64.tar.gz",
        verified: "github.com/hilli/imapsync-go/"
    end
    on_intel do
      sha256 "eb69d349fbe38b98171b5d586647682b2c4a1a457687566220e50431f68f33b7"
      url "https://github.com/hilli/imapsync-go/releases/download/v#{version}/imapsync-go_Linux_x86_64.tar.gz",
        verified: "github.com/hilli/imapsync-go/"
    end
  end

  name "imapsync-go"
  desc "Concurrent IMAP account synchronisation"
  homepage "https://github.com/hilli/imapsync-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imapsync-go"
  bash_completion "completions/imapsync-go.bash"
  fish_completion "completions/imapsync-go.fish"
  zsh_completion "completions/imapsync-go.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/imapsync-go"]
    end
  end

  # No zap stanza required
end
