# This file was generated by GoReleaser. DO NOT EDIT.
cask "kefw2ui" do
  name "kefw2ui"
  desc "Web UI for controlling KEF W2 speakers"
  homepage "https://github.com/hilli/kefw2ui"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kefw2ui"

  on_macos do
    on_intel do
      url "https://github.com/hilli/kefw2ui/releases/download/v#{version}/kefw2ui_Darwin_x86_64.tar.gz",
        verified: "github.com/hilli/kefw2ui/"
      sha256 "0cde322bf673c194b588c305fd8003160e634840cab0e40eaa23db791da0c33b"
    end
    on_arm do
      url "https://github.com/hilli/kefw2ui/releases/download/v#{version}/kefw2ui_Darwin_arm64.tar.gz",
        verified: "github.com/hilli/kefw2ui/"
      sha256 "9fd1b480ad7a8577cffcc1655be6dead55f18a648a1e20fd60dde67585af590b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hilli/kefw2ui/releases/download/v#{version}/kefw2ui_Linux_x86_64.tar.gz",
        verified: "github.com/hilli/kefw2ui/"
      sha256 "ac0f238d35b04678a449356e6cdc80d33bca9d05835fff6b8b99b4134d305e6e"
    end
    on_arm do
      url "https://github.com/hilli/kefw2ui/releases/download/v#{version}/kefw2ui_Linux_arm64.tar.gz",
        verified: "github.com/hilli/kefw2ui/"
      sha256 "cf993d9bb0a9194b4452e8a918914ecd54f9801f22ccbce3396241a04766db53"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kefw2ui"]
    end
  end

  # No zap stanza required
end
