# This file was generated by GoReleaser. DO NOT EDIT.
cask "kefw2" do
  name "kefw2"
  desc "CLI for controlling KEF W2 platform speakers"
  homepage "https://github.com/hilli/go-kef-w2"
  version "0.2.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kefw2"
  bash_completion "completions/kefw2.bash"
  zsh_completion "completions/kefw2.zsh"
  fish_completion "completions/kefw2.fish"

  on_macos do
    on_intel do
      url "https://github.com/hilli/go-kef-w2/releases/download/v#{version}/go-kef-w2_Darwin_x86_64.tar.gz",
        verified: "github.com/hilli/go-kef-w2/"
      sha256 "613a9a3ad4b692634f9babf41384ad424262570a39392f951775f1dc9b7664aa"
    end
    on_arm do
      url "https://github.com/hilli/go-kef-w2/releases/download/v#{version}/go-kef-w2_Darwin_arm64.tar.gz",
        verified: "github.com/hilli/go-kef-w2/"
      sha256 "a6b926c2ce7f1cebff00828ad4b526d2ce89979c8678fa58fbd74b68ebdaed18"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hilli/go-kef-w2/releases/download/v#{version}/go-kef-w2_Linux_x86_64.tar.gz",
        verified: "github.com/hilli/go-kef-w2/"
      sha256 "fe6b8097bd19cb0dca61c4fed9a9385a8d5f01c39d54319cc56c21819a5f5812"
    end
    on_arm do
      url "https://github.com/hilli/go-kef-w2/releases/download/v#{version}/go-kef-w2_Linux_arm64.tar.gz",
        verified: "github.com/hilli/go-kef-w2/"
      sha256 "2cf5710e3eb57e5bc945d789c91375b3c5417a43fecc02ef6adf3e6672b9f0fd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kefw2"]
    end
  end

  # No zap stanza required
end
