# This file was generated by GoReleaser. DO NOT EDIT.
cask "mac-wifi-cleaner" do
  name "mac-wifi-cleaner"
  desc "Clean up the long list of preferred Wi-Fi networks on your Mac"
  homepage "https://github.com/hilli/mac-wifi-cleaner"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mac-wifi-cleaner"

  on_macos do
    on_intel do
      url "https://github.com/hilli/mac-wifi-cleaner/releases/download/v#{version}/mac-wifi-cleaner_Darwin_x86_64.tar.gz",
        verified: "github.com/hilli/mac-wifi-cleaner"
      sha256 "4acc4331e97a0dd6f97a04f109fab05cf46625cbc66a6b765d09314cf721f9c6"
    end
    on_arm do
      url "https://github.com/hilli/mac-wifi-cleaner/releases/download/v#{version}/mac-wifi-cleaner_Darwin_arm64.tar.gz",
        verified: "github.com/hilli/mac-wifi-cleaner"
      sha256 "8a95a3af970f8bb4b528be2fefa798e24071d9e8ea990d5df41fe2f0330dbd6d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mac-wifi-cleaner"]
    end
  end

  # No zap stanza required
end
