# This file was generated by GoReleaser. DO NOT EDIT.
cask "sievemgmt" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9c5f6a07e2788ec554ce20cd049cffb52b88786f32fca52802197c352c03c526"
      url "https://github.com/hilli/sievemgmt/releases/download/v#{version}/sievemgmt_Darwin_x86_64.tar.gz",
        verified: "github.com/hilli/sievemgmt"
    end
    on_arm do
      sha256 "561dee6d146b3f73ccd1c80b302cd367c99c324cd2070aa81b471b38d72a434d"
      url "https://github.com/hilli/sievemgmt/releases/download/v#{version}/sievemgmt_Darwin_arm64.tar.gz",
        verified: "github.com/hilli/sievemgmt"
    end
  end

  on_linux do
    on_intel do
      sha256 "e71ecc3944e74f25cc14b3cd068debcf3e2cc12f7ab83b0e53c0dd0d1e6ad9c6"
      url "https://github.com/hilli/sievemgmt/releases/download/v#{version}/sievemgmt_Linux_x86_64.tar.gz",
        verified: "github.com/hilli/sievemgmt"
    end
    on_arm do
      sha256 "acfb7bdf852c7736dfd452fbee0d5e9d9a5a648809156ec0bc20b1224dccbf9d"
      url "https://github.com/hilli/sievemgmt/releases/download/v#{version}/sievemgmt_Linux_arm64.tar.gz",
        verified: "github.com/hilli/sievemgmt"
    end
  end

  name "sievemgmt"
  desc "CLI to manage Sieve scripts on a remote ManageSieve server"
  homepage "https://github.com/hilli/sievemgmt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sievemgmt"
  bash_completion "completions/sievemgmt.bash"
  fish_completion "completions/sievemgmt.fish"
  zsh_completion "completions/sievemgmt.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sievemgmt"]
    end
  end

  # No zap stanza required

end
