# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AnniversariesCal < Formula
  desc "Generate interesting date calculations from birthdates, events, and marriages"
  homepage "https://github.com/hilli/anniversaries-cal"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hilli/anniversaries-cal/releases/download/v0.0.2/anniversaries-cal_Darwin_x86_64.tar.gz"
      sha256 "8d5c36fe51a4b1a34c962267c4c9974933ccda205d788ca77efc4833a25f40e7"

      def install
        bin.install "anniversaries-cal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hilli/anniversaries-cal/releases/download/v0.0.2/anniversaries-cal_Darwin_arm64.tar.gz"
      sha256 "83462ea0da2ad7854ff04a3b256938331ab070e3ddeaf728af602b1b01ac41d9"

      def install
        bin.install "anniversaries-cal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hilli/anniversaries-cal/releases/download/v0.0.2/anniversaries-cal_Linux_x86_64.tar.gz"
      sha256 "3b7f19e4ca3c75a67a2a571197a5bc315e39296b244eb01b8cf96680ab504625"
      def install
        bin.install "anniversaries-cal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hilli/anniversaries-cal/releases/download/v0.0.2/anniversaries-cal_Linux_arm64.tar.gz"
      sha256 "1f94761c7d96d3526428156a497a4df637582c8cbb61f5aea935376c9f785628"
      def install
        bin.install "anniversaries-cal"
      end
    end
  end
end
