# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AnniversariesCal < Formula
  desc "Generate interesting date calculations from birthdates, events, and marriages"
  homepage "https://github.com/hilli/anniversaries-cal"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hilli/anniversaries-cal/releases/download/v0.0.4/anniversaries-cal_Darwin_x86_64.tar.gz"
      sha256 "53935fb0ccb41ba8398f2670a51e88e33e60c66f17220504b0631ec9c56d845f"

      define_method(:install) do
        bin.install "anniversaries-cal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hilli/anniversaries-cal/releases/download/v0.0.4/anniversaries-cal_Darwin_arm64.tar.gz"
      sha256 "299651ef842e5087ccfc85c2f3c80edeac91bfc975db854008e9d661ad42e7be"

      define_method(:install) do
        bin.install "anniversaries-cal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hilli/anniversaries-cal/releases/download/v0.0.4/anniversaries-cal_Linux_x86_64.tar.gz"
      sha256 "3fbfe7f712541d84c7e2caacb95c0010ada41c143aa1b2d680242ee954a6f3a3"
      define_method(:install) do
        bin.install "anniversaries-cal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hilli/anniversaries-cal/releases/download/v0.0.4/anniversaries-cal_Linux_arm64.tar.gz"
      sha256 "10d8f8672c6179928a93811af8bbef72c29a4a3ef5784c144301582d4f492e3a"
      define_method(:install) do
        bin.install "anniversaries-cal"
      end
    end
  end
end
