# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icat < Formula
  desc "Command line tool for displaying images in the terminal"
  homepage "https://github.com/hilli/icat"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hilli/icat/releases/download/v0.0.3/icat_Darwin_x86_64.tar.gz"
      sha256 "5994a317c3c012b1c67a967a1fef621f2a163509c284443969d5d1b816ab8286"

      def install
        bin.install "icat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hilli/icat/releases/download/v0.0.3/icat_Darwin_arm64.tar.gz"
      sha256 "4e8acc7e1377b8987981fc97eae27d68b3c514644d472abe902ddd17200c817a"

      def install
        bin.install "icat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hilli/icat/releases/download/v0.0.3/icat_Linux_x86_64.tar.gz"
        sha256 "b0a82b902167c494f8e61fc91055d84a156c6f6e860ae066d1dac839615282f4"

        def install
          bin.install "icat"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hilli/icat/releases/download/v0.0.3/icat_Linux_arm64.tar.gz"
        sha256 "526480e6ec092b40e5de546c2ca9e0205c6baa9b4453470354addcc85e607b0c"

        def install
          bin.install "icat"
        end
      end
    end
  end
end
