# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icat < Formula
  desc "Command line tool for displaying images in the terminal"
  homepage "https://github.com/hilli/icat"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hilli/icat/releases/download/v0.0.3/icat_Darwin_x86_64.tar.gz"
      sha256 "fe1677c1d07643406f7d46c68d19dd7cee45086f359537fdd04bc48581e28fcb"

      def install
        bin.install "icat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hilli/icat/releases/download/v0.0.3/icat_Darwin_arm64.tar.gz"
      sha256 "258eb0290fbb28bf6f13082a9b2d613f718c0a5af64bd0e968a22e542fa622fa"

      def install
        bin.install "icat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hilli/icat/releases/download/v0.0.3/icat_Linux_x86_64.tar.gz"
        sha256 "f35a55cd157f646ac452e30a2615fc02555450d45cbfffbd539dcdd55fa9c9a0"

        def install
          bin.install "icat"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hilli/icat/releases/download/v0.0.3/icat_Linux_arm64.tar.gz"
        sha256 "336139aeaf9efcd35d38cd796b3302c9ea4538af869ed1f03f935143d0838e5a"

        def install
          bin.install "icat"
        end
      end
    end
  end
end
