# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kefw2 < Formula
  desc "Command for handling KEF W2 platform speakers (LSX Wireless II (LT)/LS50 Wireless II/LS60 Wireless)"
  homepage "https://github.com/hilli/go-kef-w2"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hilli/go-kef-w2/releases/download/v0.2.0/go-kef-w2_Darwin_x86_64.tar.gz"
      sha256 "dabbbfd2d7550b7c96cc2c8e72981774c38ffcc4297ad3cc54af5635f56e3fb9"

      def install
        bin.install "kefw2"
        bash_completion.install "completions/kefw2.bash" => "kefw2"
        zsh_completion.install "completions/kefw2.zsh" => "_kefw2"
        fish_completion.install "completions/kefw2.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hilli/go-kef-w2/releases/download/v0.2.0/go-kef-w2_Darwin_arm64.tar.gz"
      sha256 "1d852a23c6860c128211472566fc629b5ecc127c2815e2cb95049d5a95377630"

      def install
        bin.install "kefw2"
        bash_completion.install "completions/kefw2.bash" => "kefw2"
        zsh_completion.install "completions/kefw2.zsh" => "_kefw2"
        fish_completion.install "completions/kefw2.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hilli/go-kef-w2/releases/download/v0.2.0/go-kef-w2_Linux_x86_64.tar.gz"
      sha256 "cb710916af719ee1c5ff3f96eb0f924c9a586bf22b5f09032155b8c62ea83ec6"
      def install
        bin.install "kefw2"
        bash_completion.install "completions/kefw2.bash" => "kefw2"
        zsh_completion.install "completions/kefw2.zsh" => "_kefw2"
        fish_completion.install "completions/kefw2.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hilli/go-kef-w2/releases/download/v0.2.0/go-kef-w2_Linux_arm64.tar.gz"
      sha256 "33c9f3c24320d27c981bc4aadd46b7557d85c559dfcd658f7e42f8b3422bdaf2"
      def install
        bin.install "kefw2"
        bash_completion.install "completions/kefw2.bash" => "kefw2"
        zsh_completion.install "completions/kefw2.zsh" => "_kefw2"
        fish_completion.install "completions/kefw2.fish"
      end
    end
  end
end
