# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kefw2 < Formula
  desc "Command for handling KEF W2 platform speakers (LSX Wireless II (LT)/LS50 Wireless II/LS60 Wireless)"
  homepage "https://github.com/hilli/go-kef-w2"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hilli/go-kef-w2/releases/download/v0.0.1/go-kef-w2_Darwin_x86_64.tar.gz"
      sha256 "d0d3f49b7497141c064ddb38c7102f8b7cc8b4520efe3f70e1d4969c94b481cd"

      def install
        bin.install "kefw2"
        bash_completion.install "completions/kefw2.bash" => "kefw2"
        zsh_completion.install "completions/kefw2.zsh" => "_kefw2"
        fish_completion.install "completions/kefw2.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hilli/go-kef-w2/releases/download/v0.0.1/go-kef-w2_Darwin_arm64.tar.gz"
      sha256 "dbf3d41e0273d9fd1ca3e50170f2b3b9f61a76c583e2d5fe16a332bae7f5e337"

      def install
        bin.install "kefw2"
        bash_completion.install "completions/kefw2.bash" => "kefw2"
        zsh_completion.install "completions/kefw2.zsh" => "_kefw2"
        fish_completion.install "completions/kefw2.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hilli/go-kef-w2/releases/download/v0.0.1/go-kef-w2_Linux_arm64.tar.gz"
      sha256 "71cdcb69cc77ab3cb05f5f789e682a7e7029f995ac0a36893bc59ff5ad25a62d"

      def install
        bin.install "kefw2"
        bash_completion.install "completions/kefw2.bash" => "kefw2"
        zsh_completion.install "completions/kefw2.zsh" => "_kefw2"
        fish_completion.install "completions/kefw2.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hilli/go-kef-w2/releases/download/v0.0.1/go-kef-w2_Linux_x86_64.tar.gz"
      sha256 "3127cd80d3cd4ca26717e80b1d686c7c4bced856d038bad81f9575b74dcdf3fe"

      def install
        bin.install "kefw2"
        bash_completion.install "completions/kefw2.bash" => "kefw2"
        zsh_completion.install "completions/kefw2.zsh" => "_kefw2"
        fish_completion.install "completions/kefw2.fish"
      end
    end
  end
end
